run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - exportloopref
    - bodyclose
    - noctx
    - sqlclosecheck
    - rowserrcheck
    - gosec
    - errorlint

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable:
      - shadow
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/thenexusengine/tne_springwire
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    for-loops: true
  gosec:
    excludes:
      - G104 # Audit errors not checked (we handle these intentionally in some places)
    config:
      G306: "0644" # Expected file permissions

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

    # Exclude known issues in generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all

  max-issues-per-linter: 50
  max-same-issues: 10

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
